--1.CUSTOMERS WITH NO ORDERS
SELECT USERS.FIRST_NAME,USERS.LAST_NAME
FROM USERS
LEFT JOIN  CART ON USERS.ID=CART.USER_ID
WHERE CART.USER_ID IS NULL;

--2.TOP 5 users
SELECT FIRST_NAME , LAST_NAME,AMOUNT  
FROM USERS JOIN CART ON USERS.ID=CART.USER_ID ORDER BY AMOUNT DESC
LIMIT 5;

--top 5 orders
SELECT * FROM CART
ORDER BY AMOUNT DESC
LIMIT 5;

--top 5 most selling products

 SELECT PRODUCT_ID,SUM(QUANTITY_WISHED) AS TOTAL_QUANTITY
 FROM CART_ITEM JOIN PRODUCTS ON CART_ITEM.PRODUCT_ID=PRODUCTS.ID
 GROUP BY PRODUCT_ID
 ORDER BY TOTAL_QUANTITY DESC
 LIMIT 5;

--3.City Wise Users Count
SELECT CITY,COUNT(USER_ID)
FROM ADDRESSES
GROUP BY CITY
ORDER BY COUNT(USER_ID) DESC

--4.total amount of orders receive till a particular time_frame
SELECT SUM(TOTAL_AMOUNT) AS 'REVENUE'  
FROM PAYMENT
WHERE CREATED_AT BETWEEN '2022-01-11 00:00:00' AND '2022-01-11 18:00:00'

--5.orders having amount greater than AVG
SELECT * 
FROM  CART a
WHERE AMOUNT >
    (SELECT AVG(AMOUNT) FROM CART b 
     );

--6.Give discount of 2000 To All In Cart Orders
UPDATE CART 
SET 
    DISCOUNT = CASE AMOUNT
WHEN AMOUNT >2000 THEN 2000 ELSE AMOUNT END;